import unittest

from unittest.mock import Mock, MagicMock


class TestAPICallWithRetry(unittest.TestCase):

    def test_api_call_with_retry_on_429(self):
        pass
